export const listRuangan = [
  "Poli BKIA",
  "Fisioterapi",
  "Rehab Medis",
  "Poli Fisioterapi",
  "Poli Jantung Anak",
  "IGD Zona Hijau",
  "Poli Gizi",
  "Klinik Eksekutif  Anak",
  "KLINIK HOMECARE",
  "Poli Jantung (Pagi)",
  "Poli Ortopedi (Pagi)",
  "Poli Bedah Umum (Pagi)",
  "Poli Bedah Umum (Siang)",
  "Poli Ortopedi (Malam)",
  "Poli Jantung (Malam)",
  "Poli Gigi (Pagi)",
  "Poli Gigi (Siang)",
  "Poli Gigi (Malam)",
  "Poli Rehab Medik",
  "Poli THT",
  "Poli Kulit & Kelamin",
  "Poli Bedah Umum",
  "Poli Anak",
  "Poli Kebidanan dan Kandungan",
  "Poli Jantung",
  "Poli Kebidanan dan Kandungan (Malam/Khusus Umum)",
  "Poli Anak (Siang)",
  "Poli Kebidanan dan Kandungan (Siang)",
  "Poli Saraf (Siang)",
  "Poli Saraf (Malam)",
  "Poli Bedah Umum (Malam)",
  "Poli Ortopedi (Siang)",
  "Poli Bedah Umum (Sore)\t",
  "Poli Ortopedi (Sore)",
  "Poli Paru(Sore)",
  "Poli Kulit & Kelamin (Siang)",
  "Poli Kulit & Kelamin (Sore)",
  "Poli Psikiatri/ Jiwa (Pagi)",
  "Poli Urologi (Pagi)",
  "Poli Gigi (Sore)",
  "Poli Urologi (Siang)",
  "Poli Urologi (Malam)",
  "Poli Gigi Endodonsi(Sore)",
  "Poli Gigi Spesialis",
  "Poli Gigi Endodonsi (Pagi)",
  "Poli Mata (Malam)",
  "Poli Mata",
  "Poli Jantung (Sore)",
  "Poli Psikiatri/ Jiwa",
  "Poli Saraf",
  "Poli Paru",
  "Poli Ortopedi",
  "Poli Urologi",
  "Poli Saraf (Pagi)",
  "Poli Saraf (Sore)",
  "Poli THT (Sore)",
  "Poli Jantung (Siang)",
  "Poli Anak (Malam/Khusus Umum)",
  "Poli Gigi Umum",
  "Klinik MCU",
  "Poli Kebidanan dan Kandungan (Pagi)",
  "Poli Penyakit Dalam (Siang)",
  "Poli Jantung Khusus Echo (Siang)",
  "Poli Jantung Khusus Echo (Malam)",
  "Poli Anak (Sore)",
  "Poli Urologi (Sore)",
  "Poli Rehab Medik (Sore)",
  "Poli Kebidanan dan Kandungan (Sabtu/Khusus Umum)\t",
  "Poli Rehab Medik (Pagi)",
  "Poli Rehab Medik (Siang)",
  "SENAM HAMIL",
  "Poli Kebidanan dan Kandungan (Sore)",
  "Poli Gigi Endodonsi (Malam)",
  "Poli Kebidanan dan Kandungan Hari Minggu (Umum)",
  "Poli Anak Pagi (Vaksin)",
  "Poli Kulit & Kelamin (Pagi)",
  "Poli Gigi Orthodonsi",
  "Terapi Wicara/Okupasi 1x (Kunjungan Pertama)",
  "Terapi Wicara/Okupasi 4x (Kunjungan Pertama)",
  "Poli Psikiatri/ Jiwa (Sore)",
  "Terapi Wicara/Okupasi (Kunjungan 2-8)",
  "Poli Kebidanan dan Kandungan (Malam)",
  "Poli Rehab Medik (Anak)",
  "Poli Gigi Endodonsi (Siang)",
  "Poli Paru (Pagi)",
  "Poli Gigi Pedodonsi",
  "Klinik Eksekutif Jantung",
  "Klinik Eksekutif Urologi",
  "Klinik Eksekutif Bedah Umum (Sore)",
  "Klinik Eksekutif Saraf",
  "Klinik Eksekutif Bedah Umum (Malam)",
  "Klinik Eksekutif Kulit dan Kelamin",
  "Poli Anak Khusus Bayi Sehat,Post MRS,Vaksin",
  "Klinik Eksekutif Orthopedi (Sore)",
  "Klinik Eksekutif Orthopedi (Malam)",
  "Klinik Eksekutif Penyakit Dalam (Pagi)",
  "Klinik Eksekutif Penyakit Dalam (Sore)",
  "Klinik Eksekutif THT",
  "Klinik Eksekutif Psikiatri",
  "Poli Mata (Pagi)",
  "Poli Mata (Siang)",
  "Poli Mata (Sore)",
  "Poli THT (Pagi)",
  "Poli Anak (Pagi)",
  "Poli Anak Siang",
  "Poli Anak Sore",
  "Klinik Eksekutif  Anak Malam",
  "Hemodialisa",
  "Klinik TB-DM",
  "Klinik VCT",
  "Klinik Eksekutif  Anak Sore",
  "Poli Penyakit Dalam (Pagi)",
  "Poli Penyakit Dalam",
  "Poli Penyakit Dalam (Malam)",
  "Poli Penyakit Dalam (Sore)",
];
