import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
          "6": "hsl(var(--chart-6))",
          "7": "hsl(var(--chart-7))",
          "8": "hsl(var(--chart-8))",
          "9": "hsl(var(--chart-9))",
          "10": "hsl(var(--chart-10))",
          "11": "hsl(var(--chart-11))",
          "12": "hsl(var(--chart-12))",
          "13": "hsl(var(--chart-13))",
          "14": "hsl(var(--chart-14))",
          "15": "hsl(var(--chart-15))",
          "16": "hsl(var(--chart-16))",
          "17": "hsl(var(--chart-17))",
          "18": "hsl(var(--chart-18))",
          "19": "hsl(var(--chart-19))",
          "20": "hsl(var(--chart-20))",
          "21": "hsl(var(--chart-21))",
          "22": "hsl(var(--chart-22))",
          "23": "hsl(var(--chart-23))",
          "24": "hsl(var(--chart-24))",
          "25": "hsl(var(--chart-25))",
          "26": "hsl(var(--chart-26))",
          "27": "hsl(var(--chart-27))",
          "28": "hsl(var(--chart-28))",
          "29": "hsl(var(--chart-29))",
          "30": "hsl(var(--chart-30))",
          "31": "hsl(var(--chart-31))",
          "32": "hsl(var(--chart-32))",
          "33": "hsl(var(--chart-33))",
          "34": "hsl(var(--chart-34))",
          "35": "hsl(var(--chart-35))",
          "36": "hsl(var(--chart-36))",
          "37": "hsl(var(--chart-37))",
          "38": "hsl(var(--chart-38))",
          "39": "hsl(var(--chart-39))",
          "40": "hsl(var(--chart-40))",
          "41": "hsl(var(--chart-41))",
          "42": "hsl(var(--chart-42))",
          "43": "hsl(var(--chart-43))",
          "44": "hsl(var(--chart-44))",
          "45": "hsl(var(--chart-45))",
          "46": "hsl(var(--chart-46))",
          "47": "hsl(var(--chart-47))",
          "48": "hsl(var(--chart-48))",
          "49": "hsl(var(--chart-49))",
          "50": "hsl(var(--chart-50))",
          "51": "hsl(var(--chart-51))",
          "52": "hsl(var(--chart-52))",
          "53": "hsl(var(--chart-53))",
          "54": "hsl(var(--chart-54))",
          "55": "hsl(var(--chart-55))",
          "56": "hsl(var(--chart-56))",
          "57": "hsl(var(--chart-57))",
          "58": "hsl(var(--chart-58))",
          "59": "hsl(var(--chart-59))",
          "60": "hsl(var(--chart-60))",
          "61": "hsl(var(--chart-61))",
          "62": "hsl(var(--chart-62))",
          "63": "hsl(var(--chart-63))",
          "64": "hsl(var(--chart-64))",
          "65": "hsl(var(--chart-65))",
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
